### ISSUE TITLE
[FEATURE] Make the configurator accessible via microservice

### ISSUE THREAD

**Issue by alexlovelltroy** [OpenCHAMI/configurator#1]
As developed today, the configurator requires the user to maintain a set of locally managed template files and update the code when a new template type is added.  This user workflow is likely to lead to mutliple admins making their own local changes to the code itself and the templates.

While I really like the CLI interaction here, I also would like the ability to run this as a service inside an OpenCHAMI deployment as a shared service.  In that configuration, we'd need the ability to define and upload templates, perhaps with versioning, and have the templates executed on-demand, returning the templated file.

Preserving the standalone operation is also important for small clusters and individual admins.  They shouldn't have to install a service in order to template a file.

**Comment by davidallendj** [comment]
This was originally added with #2.
