### ISSUE TITLE
[RFD] Convert from plugin-based architecture to one that compiles everything into a single binary

### ISSUE THREAD

**Issue by alexlovelltroy** [OpenCHAMI/configurator#20]
It is my assertion that the plugin architecture is adding complexity to configurator without commensurate benefit.  

The loadable plugins architecture makes it easier for third parties to add features without recompiling the binary and provides a very clean interface for extending configurator.  However, since we deploy configurator as a containerized microservice anyway, adding plugins actually complicates the build and release process.  In addition, the complexity of versioning plugins separately from the main executable is not a solved problem in configurator.

## Proposal

While preserving the clean API for plugins and preserving the option of returning to loadable modules when the benefit is clear, we should update configurator to be able to compile in the plugins directly into the core binary and make that the default behavior.

**Comment by alexlovelltroy** [comment]
I believe this can be accomplished with build tags at the top of each plugin file and an update to the build command used to include the tags for each plugin we want to enable by default
```go
//go:build plugin1
```

### goreleaser.yaml
```yaml
builds:
    - id: "configurator"
      goos:
          - linux
      flags:
          - -tags:plugin1,plugin2,plugin3
```

**Comment by davidallendj** [comment]
Is the intention here to keep plugins but just move the default plugins into the binary? I was eventually planning to do this, but I will require some small changes even after having everything compiled into the binary.

**Comment by alexlovelltroy** [comment]
For default OpenCHAMI builds, we should include all the OpenCHAMI plugins in the binary.  If you maintain the plugin structure, you should be able to do a non-OpenCHAMI build without including the plugins by tweaking the build flags.

**Comment by alexlovelltroy** [comment]
Can you add an additional build target in .goreleaser.yaml for the binary that has no plugins included and update the main build to include all OpenCHAMI plugins?

**Comment by davidallendj** [comment]
> Can you add an additional build target in .goreleaser.yaml for the binary that has no plugins included and update the main build to include all OpenCHAMI plugins?

Yes, I'll try to get to this soon.
